#hello world yml file
- hosts: kafka
  remote_user: root
  tasks:
  - name: clean zookeeper data
    shell: /usr/bin/rm -rf /opt/data/version-2
  - name: clean kafka data
    shell: /usr/bin/rm -rf /home/kafka/data
